<?php

return [
    'apps' => [
//        'demo',
        'dragon168',
        'la168',
        'hero168',
        'fafa168',
        'vela168',
        'vegas888',
        'rich168',
        'megawin9',
//        'gb168slot',
//        'aeiou168',
        'yan798',
//        'thegrand789',
//        'slotnaga168auto',
//        'dragon168vip',
//        'galaxybet',
//        'gb168slot',
//        'atm928',
//        'huaydragon168',
//        'huaydragon88',
//        'aba888',
//        'ak168',
//        'angkor168',
//        'angkorking',
//        'angkorwin',
//        'cambo789',
//        'dimondclub',
//        'Easyfun',
//        'funkhr',
//        'heng222',
//        'gobet777',
//        'khwin789',
//        'krud168',
//        'luckybet',
//        'macau88',
//        'manee789',
//        'megawins',
//        'pg168kh',
//        'sn88',
//        'starking99',
//        'win999',
//        'win999vip',
//        'winswin888',
//        'worldbet88kh',
    ],
];
